<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
        <PackageReference Include="Scrutor" Version="7.0.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CinemaTicketing.Application\CinemaTicketing.Application.csproj" />
      <ProjectReference Include="..\CinemaTicketing.Domain\CinemaTicketing.Domain.csproj" />
      <ProjectReference Include="..\CinemaTicketing.Infrastructure\CinemaTicketing.Infrastructure.csproj" />
    </ItemGroup>

</Project>
