<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CinemaTicketing.Domain\CinemaTicketing.Domain.csproj" />
      <ProjectReference Include="..\CinemaTicketing.Shared\CinemaTicketing.Shared.csproj" />
    </ItemGroup>

</Project>
